version: "3"
volumes:
  database-data:
    driver: local
services:
  php:
    container_name: simplePayment-php
    tty: true
    build: ./docker
    volumes:
      - ./:/var/www/
      - ./docker/xdebug.ini:/etc/php82/conf.d/50_xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=${APP_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9511:9501"
    entrypoint: bash -c "./docker/entrypoint.sh"
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: simplePayment-database
    volumes:
      - database-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simplePayment
      MYSQL_TCP_PORT: 3599
    ports:
      - "3599:3599"
