###

POST {{host}}/api/transfer
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "payer": 1,
  "payee": 2,
  "value": 0.1
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Show Transactions
GET {{host}}/api/transfer
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{transaction-flux.token}}
